### PR TITLE
Adding Bitbucket Adapter

### PR DESCRIPTION
**Pull request by quantumew**
Hey Aaron, this looked like a cool project, added the bitbucket adapter for fun. Tested on bitbucket.org on v2 API. Need to test against Stash to see if it necessitates more compatibility code or maybe just another adapter if it is out of date enough.

Bitbucket only allows you to post file contents with user name and password and thus the basic auth. May be able to use OAuth "Resource Owner Password Credentials Grant" instead. Haven't tried. Currently you just have to base64 encode username:password and drop it in as the token. Not optimal but since it should be HTTPs, it should be fine. Let me know what you think.

### CODE REVIEW

**Comment by quantumew** [comment]
Whoops @aarongodin forgot to mention you. No rush obviously :-)

**Comment by aarongodin** [comment]
Thanks for the PR!

OAuth will be the way to go for all of the adapters. GitHub allows you to trade basic auth for an access token, so that seems like the way to go. https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization The way you've done it is okay for now and we can make it more consistent later.

**Comment by quantumew** [comment]
@aarongodin Thanks for the merge. Good to know, when I was testing I think the reason I had issues POSTing to /src was due to me using the incorrect grant type but I will confirm.

One more thing, I want to get front end devs using this in Best Buy. It would save a lot of time. I do need to add API v1 since we are using Bitbucket server internally (only exposes v1). I was going to do that via a config option "API Version" that defaults to v2. Then have an API interface and v1 and v2 implementations. Does that make sense to you or would you rather see a different adapter? For instance Bitbucket Server and Bitbucket Cloud.

**Comment by aarongodin** [comment]
Good point--I think different adapters is more logical, but however you want to arrange the code to share most of the adapter between Server and Cloud is fine. They could belong to the same directory but should have separate configure steps.

**Comment by aarongodin** [comment]
Also thanks for the bit of inspiration :) I think I will be able to get to some more of the items on the todo list this week to make this more reliable.

**Comment by quantumew** [comment]
@aarongodin Yea good point, separate adapters does make more sense. Yea, I have been trying to fit in more open source work so glad to work on this tool for part of that time. This is a well written, easy to use tool.

**Pull request merged**
